### ISSUE TITLE
Contact Me Here

### ISSUE THREAD

**Issue by smartnavdeep** [smartnavdeep/smartnavdeep#3]
# Hey All

If you all are new here, then you can come in touch with me and after that we can find a good way to communicate

**Comment by Natalie-Katie** [comment]
Can you be my teacher ?

**Comment by smartnavdeep** [comment]
Well I can indeed be one, but we both live on opposite side of the globe, I mean, you live in USA and I live In India, So  I think we won't be able to, sorry for that.

**Comment by Natalie-Katie** [comment]
No Problem, I can understand. I will still follow you so that I can learn something from you Mr.Navdeep.

**Comment by smartnavdeep** [comment]
Thanks For understanding, BTW I ain't still a pruh web-dev so you won't benefit anything by seeing my repos.

**Comment by Natalie-Katie** [comment]
At least you're better than me and our ages are same, that's the reason I was telling like that : )

**Comment by smartnavdeep** [comment]
Oh, So I understand, anyways, We won't be able to keep in touch with each other frequently, anyways **Congratulations on your first contribution in GitHub!**

**Comment by Natalie-Katie** [comment]
OMG thank you so much Mr.Navdeep, I didn't now that even this is a contribution in GitHub, By the way, Congratulations for you too for surpassing **500 commits and contributions!**.

**Comment by smartnavdeep** [comment]
Haha Thank you too !

**Comment by Natalie-Katie** [comment]
Your Welcome 😊😉
