### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by Ved-programmer** [smartnavdeep/smartnavdeep#6]
This is not technically an issue, but I have a question. How did you host your website on Github. I also want to host a website on Github, like you have a website https://smartnavdeep.github.io/smartnavdeep similarly I want a website too. Any ideas how I can do that?

**Comment by smartnavdeep** [comment]
Well YT tuts can help you , that’s how I learned to host the websites

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
